/**
 * Command Code's own per-model reasoning-effort registry, read from the
 * installed CLI package.
 *
 * Command Code's `--list-models` listing carries an id and a description and
 * nothing else, and its `--effort` flag accepts a fixed vocabulary that says
 * nothing about which level a given model actually takes — `deepseek/deepseek-v4-pro`
 * offers `high` and `max`, `z-ai/glm-5.3-flash` offers `low`, `high`, and `max`,
 * and `Qwen/Qwen3.8-Flash` offers `low`, `medium`, and `xhigh`. The authoritative
 * per-model answer is the catalog the CLI itself ships and validates
 * `model:effort` against: `bundled/command-code-knowledge/reference/models.md`
 * beside the installed entry point, generated by Command Code from its own
 * documentation and carrying an `Efforts` column for every id it serves.
 *
 * The registry is read lazily and once per plugin lifetime, and it is advisory
 * in exactly the way the CLI's own catalog is: a package that is absent, moved,
 * or reformatted yields an empty registry, which leaves every model undeclared
 * instead of offering a level set nobody stated.
 *
 * @module @deepseek-ai/dsh-subagent-commandcode/models
 */

import { existsSync, readFileSync, realpathSync } from 'node:fs'
import { delimiter, dirname, join } from 'node:path'
import type { LlmModelCapabilityLookup } from '@deepseek-ai/dsh-llm'
import { COMMAND_CODE_POSIX_COMMAND, resolveCommandCodeInvocation } from './cli.ts'

/** Reasoning-effort levels this reader accepts from Command Code's catalog. */
export type CommandCodeModelEfforts = readonly string[]

/** Path segments from the installed entry point to the shipped model catalog. */
const CATALOG_SEGMENTS: readonly string[] = [
  'bundled',
  'command-code-knowledge',
  'reference',
  'models.md',
]

/**
 * Locate Command Code's shipped model catalog from the installed entry point.
 * @param entryPoint - absolute path of the CLI's JavaScript entry.
 * @returns the catalog path, or undefined when the package does not ship one.
 */
export function commandCodeCatalogPath(entryPoint: string): string | undefined {
  const candidate = join(dirname(entryPoint), ...CATALOG_SEGMENTS)
  return existsSync(candidate) ? candidate : undefined
}

/** Filesystem facts entry-point resolution reads, injectable so both platforms are testable anywhere. */
export interface CommandCodeEntryInternals {
  /** Directory list from `PATH`. */
  readonly pathEntries: readonly string[]
  /** Whether a path names an existing file or directory. */
  readonly exists: (path: string) => boolean
  /** Read a shim script as text. */
  readonly readText: (path: string) => string
  /** Follow a PATH entry's link to the file it names. */
  readonly realpath: (path: string) => string
}

/**
 * Resolve the installed CLI's entry point, the anchor its shipped catalog sits
 * beside. Windows reads the npm shim the launcher invokes; elsewhere the PATH
 * entry is followed through its link, and the shipped catalog's presence is
 * what proves the path really is this package rather than an unrelated `cmd`.
 * @param platform - the running platform.
 * @param internals - injected filesystem access.
 * @returns the absolute entry point, or undefined when none can be proven.
 */
export function resolveCommandCodeEntryPoint(
  platform: NodeJS.Platform,
  internals: CommandCodeEntryInternals,
): string | undefined {
  if (platform === 'win32') {
    try {
      return resolveCommandCodeInvocation(platform, internals).prefix[0]
    } catch (_launcherUnusable) {
      // No installed launcher means no catalog to read; every model stays
      // undeclared, which is the same answer an unreadable catalog gives.
      return undefined
    }
  }
  for (const entry of internals.pathEntries) {
    if (entry.length === 0) continue
    const program = join(entry, COMMAND_CODE_POSIX_COMMAND)
    if (!internals.exists(program)) continue
    let resolved: string
    try {
      resolved = internals.realpath(program)
    } catch (_unreadableLink) {
      // A PATH entry whose link cannot be followed is not this package.
      continue
    }
    if (commandCodeCatalogPath(resolved) !== undefined) return resolved
  }
  return undefined
}

/**
 * Resolve the entry point using the running process's own PATH and filesystem.
 * @param platform - the platform whose resolution to run; defaults to the
 *   running one, and is a parameter so both registrations stay testable from
 *   either platform.
 * @returns the absolute entry point, or undefined when none can be proven.
 */
export function installedCommandCodeEntryPoint(
  platform: NodeJS.Platform = process.platform,
): string | undefined {
  return resolveCommandCodeEntryPoint(platform, {
    pathEntries: (process.env.PATH ?? '').split(delimiter),
    exists: path => existsSync(path),
    readText: path => readFileSync(path, 'utf8'),
    realpath: path => realpathSync(path),
  })
}

/**
 * Whether one discovery draft is a Command Code route this catalog describes.
 *
 * The catalog is keyed by model id alone, and Command Code serves bare ids for
 * other vendors' models (`claude-sonnet-5`, `gpt-5.4`), so answering by id for
 * every route would attribute this registry to an unrelated provider. A route
 * therefore has to name Command Code itself: its endpoint on a `commandcode.ai`
 * host, or a route id that names the CLI.
 * @param request - the draft being interrogated.
 * @returns whether this source owns that route.
 */
export function commandsCodeRouteOwns(request: { provider?: string; baseURL?: string }): boolean {
  const named = (request.provider ?? '').toLowerCase().replace(/[^a-z0-9]/gu, '')
  if (named.includes('commandcode') || named === 'cmd' || named === 'cmdc' || named === 'cc') return true
  const baseURL = request.baseURL
  if (baseURL === undefined || baseURL.length === 0) return false
  try {
    const host = new URL(baseURL).hostname.toLowerCase()
    return host === 'commandcode.ai' || host.endsWith('.commandcode.ai')
  } catch (_unparseableURL) {
    // An endpoint that is not a URL cannot be shown to be Command Code's.
    return false
  }
}

/**
 * Parse the catalog's per-model effort column.
 *
 * Rows are the generated table's model lines; the id is its first cell and the
 * offered levels its fourth. An em dash, a dash, or an empty cell is the
 * catalog stating that the model decides its own reasoning depth, which yields
 * no levels rather than an assumption. Every other cell is split into its
 * comma-separated levels, trimmed, and preserved exactly — a level Command Code
 * names differently is carried through unchanged for the seam's normalization
 * to accept or drop, never translated here.
 * @param markdown - the catalog's text.
 * @returns effort levels by exact model id, omitting models that offer none.
 */
export function parseCommandCodeModelEfforts(markdown: string): Map<string, CommandCodeModelEfforts> {
  const efforts = new Map<string, CommandCodeModelEfforts>()
  for (const raw of markdown.split(/\r?\n/u)) {
    if (!raw.startsWith('|')) continue
    const cells = raw.split('|')
    const idCell = cells[1]
    const effortsCell = cells[4]
    // A line without both columns this reader is defined by — a heading, the
    // separator row, prose — states nothing about any model.
    if (idCell === undefined || effortsCell === undefined) continue
    const id = /^`([^`]+)`$/u.exec(idCell.trim())?.[1]
    if (id === undefined) continue
    const stated = effortsCell
      .split(',')
      .map(level => level.trim())
      .filter(level => level.length > 0 && level !== '—' && level !== '-')
    if (stated.length === 0) continue
    efforts.set(id, stated)
  }
  return efforts
}

/**
 * Read the installed catalog.
 * @param entryPoint - absolute path of the CLI's JavaScript entry.
 * @returns effort levels by model id; empty when no readable catalog exists.
 */
export function loadCommandCodeModelEfforts(
  entryPoint: string,
): Map<string, CommandCodeModelEfforts> {
  const path = commandCodeCatalogPath(entryPoint)
  if (path === undefined) return new Map()
  try {
    return parseCommandCodeModelEfforts(readFileSync(path, 'utf8'))
  } catch (_unreadableCatalog) {
    // A catalog this process cannot read leaves every model undeclared, which is
    // the same answer a catalog that states nothing gives. Propagating instead
    // would fail a model-discovery fetch over a documentation asset.
    return new Map()
  }
}

/**
 * Build the capability source this integration contributes to model discovery.
 *
 * The catalog is resolved and read once, on the first lookup, so mounting the
 * plugin touches no files; a plugin whose CLI is not installed answers nothing
 * for every model. The source answers only for routes that name Command Code or
 * point at a Command Code endpoint, because the catalog is keyed by model id
 * and those ids are not unique across providers.
 * @param entryPoint - resolves the installed CLI's entry point; injectable so
 *   the source is testable without an installation.
 * @returns the lookup to register on the LLM service.
 */
export function createCommandCodeCapabilitySource(
  entryPoint: () => string | undefined = installedCommandCodeEntryPoint,
): LlmModelCapabilityLookup {
  let efforts: Map<string, CommandCodeModelEfforts> | undefined
  return (modelId, request) => {
    if (!commandsCodeRouteOwns(request)) return undefined
    if (efforts === undefined) {
      const installed = entryPoint()
      efforts = installed === undefined ? new Map() : loadCommandCodeModelEfforts(installed)
    }
    const stated = efforts.get(modelId)
    return stated === undefined ? undefined : { reasoningEfforts: stated }
  }
}
