import { spawnSync } from 'node:child_process'
import { cpSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import {
  committedGeneratedAt,
  parseRequest,
  readCapture,
  readInputs,
  renderSnapshotModule,
  SNAPSHOT_PATH,
} from './gen-model-capability-snapshot.ts'

const root = resolve(import.meta.dirname, '..')

/** A curated capture the tests can regenerate from without touching the repository. */
const MODELS_DEV_INPUT = 'packages/llm/model-capabilities/tests/fixtures/upstream/models-dev.json'
/** The OpenRouter capture the tests regenerate from. */
const OPENROUTER_INPUT = 'packages/llm/model-capabilities/tests/fixtures/upstream/openrouter.json'

/**
 * Run the generator as the repository's scripts invoke it.
 * @param args - command-line arguments after the script path.
 * @returns the settled process.
 */
function runGenerator(args: readonly string[]) {
  return spawnSync(
    process.execPath,
    ['node_modules/tsx/dist/cli.mjs', 'scripts/gen-model-capability-snapshot.ts', ...args],
    { cwd: root, encoding: 'utf8' },
  )
}

describe('the snapshot generator command line', () => {
  it('defaults to checking nothing and reading the committed captures', () => {
    expect(parseRequest([])).toEqual({
      check: false,
      modelsDevInput: MODELS_DEV_INPUT,
      openRouterInput: OPENROUTER_INPUT,
      output: SNAPSHOT_PATH,
    })
  })

  it('accepts every override it documents', () => {
    expect(parseRequest(['--check', '--models-dev', 'a.json', '--openrouter', 'b.json', '--out', 'c.json']))
      .toEqual({
        check: true,
        modelsDevInput: 'a.json',
        openRouterInput: 'b.json',
        output: 'c.json',
      })
    expect(parseRequest(['--generated-at', '2026-09-16T00:00:00.000Z']).generatedAt)
      .toBe('2026-09-16T00:00:00.000Z')
  })

  it('refuses an unknown flag and a flag with no value', () => {
    expect(() => parseRequest(['--unknown'])).toThrow(/unknown flag --unknown/u)
    expect(() => parseRequest(['--models-dev'])).toThrow(/--models-dev needs a value/u)
  })
})

describe('reading the captures', () => {
  it('returns the parsed document and the digest of the bytes it was read from', () => {
    const capture = readCapture(MODELS_DEV_INPUT)
    expect(Object.keys(capture.document as Record<string, unknown>)).toEqual(['providers'])
    expect(capture.digest).toMatch(/^[0-9a-f]{64}$/)
  })

  it('reads both captures the snapshot needs', () => {
    expect(readInputs(parseRequest([]))).toMatchObject({
      modelsDevInput: MODELS_DEV_INPUT,
      openRouterInput: OPENROUTER_INPUT,
    })
  })

  it('fails loud for a capture that is not there', () => {
    expect(() => readCapture('does/not/exist.json')).toThrow(/ENOENT/u)
  })
})

describe('rendering the artifact', () => {
  it('emits a module whose banner says it is generated and whose data is a literal', () => {
    const rendered = renderSnapshotModule({
      schemaVersion: 1,
      generatedAt: '2026-09-16T00:00:00.000Z',
      sources: {
        'models.dev': { input: 'a.json', digest: 'a'.repeat(64), entryCount: 1 },
        openrouter: { input: 'b.json', digest: 'b'.repeat(64), entryCount: 1 },
      },
      catalogs: { modelsDev: {}, openRouter: { data: [] } },
    })
    expect(rendered.startsWith('/**\n * Generated by scripts/gen-model-capability-snapshot.ts')).toBe(true)
    expect(rendered).toContain("import type { ModelCapabilitySnapshot } from '../snapshot.ts'")
    expect(rendered).toContain('export const snapshotModule: ModelCapabilitySnapshot = {')
    expect(rendered).toContain('\n  "schemaVersion": 1,')
    expect(rendered.endsWith('}\n')).toBe(true)
    expect(rendered.endsWith('\n\n')).toBe(false)
  })
})

describe('reading the committed timestamp', () => {
  it('answers the committed module’s own timestamp without importing it', () => {
    const stated = /^ {2}"generatedAt": "([^"]+)",$/mu.exec(readFileSync(resolve(root, SNAPSHOT_PATH), 'utf8'))?.[1]
    expect(stated).toMatch(/^\d{4}-\d{2}-\d{2}T/u)
    expect(committedGeneratedAt(SNAPSHOT_PATH)).toBe(stated)
  })

  it('answers nothing for an artifact that is absent or states no timestamp', () => {
    expect(committedGeneratedAt('does/not/exist.ts')).toBeUndefined()
    const scratch = mkdtempSync(join(tmpdir(), 'snapshot-timestamp-'))
    try {
      const notASnapshot = join(scratch, 'not-a-snapshot.ts')
      writeFileSync(notASnapshot, 'export const snapshotModule = {}\n')
      expect(committedGeneratedAt(notASnapshot)).toBeUndefined()
      const notText = join(scratch, 'empty.ts')
      writeFileSync(notText, '')
      expect(committedGeneratedAt(notText)).toBeUndefined()
    } finally {
      rmSync(scratch, { recursive: true, force: true })
    }
  })
})

describe('the freshness gate', () => {
  it('passes for the committed artifact and never rewrites it', () => {
    const before = readFileSync(resolve(root, SNAPSHOT_PATH), 'utf8')
    const result = runGenerator(['--check'])
    expect(result.stderr).toBe('')
    expect(result.stdout).toMatch(/is fresh \(\d+ models\.dev provider\(s\), \d+ OpenRouter model\(s\), generated \d{4}-/u)
    expect(result.status).toBe(0)
    expect(readFileSync(resolve(root, SNAPSHOT_PATH), 'utf8')).toBe(before)
  })

  it('fails when the source content moved away from the artifact', () => {
    const scratch = mkdtempSync(join(tmpdir(), 'snapshot-stale-'))
    try {
      const stale = join(scratch, 'models-dev.json')
      const capture = readFileSync(resolve(root, MODELS_DEV_INPUT), 'utf8')
      cpSync(resolve(root, MODELS_DEV_INPUT), stale)
      writeFileSync(stale, capture.replace('"low"', '"turbo"'))
      const output = join(scratch, 'out.ts')
      writeFileSync(output, readFileSync(resolve(root, SNAPSHOT_PATH), 'utf8'))

      const result = runGenerator(['--check', '--models-dev', stale, '--openrouter', OPENROUTER_INPUT, '--out', output])
      expect(result.status).toBe(1)
      expect(result.stderr).toMatch(/is stale against/u)
      expect(result.stderr).toMatch(/first difference at line \d+/u)
      expect(result.stderr).toMatch(/run `pnpm run gen-model-capability-snapshot`/u)
      // A check run leaves both the artifact and the scratch copy alone.
      expect(readFileSync(output, 'utf8')).toBe(readFileSync(resolve(root, SNAPSHOT_PATH), 'utf8'))
      expect(readFileSync(stale, 'utf8')).toContain('"turbo"')
    } finally {
      rmSync(scratch, { recursive: true, force: true })
    }
  })

  it('fails for an artifact that is missing entirely', () => {
    const scratch = mkdtempSync(join(tmpdir(), 'snapshot-missing-'))
    try {
      const result = runGenerator([
        '--check',
        '--models-dev', MODELS_DEV_INPUT,
        '--openrouter', OPENROUTER_INPUT,
        '--out', join(scratch, 'absent.ts'),
      ])
      expect(result.status).toBe(1)
      expect(result.stderr).toMatch(/is stale against/u)
      expect(result.stderr).toMatch(/is missing\. Run `pnpm run gen-model-capability-snapshot`/u)
    } finally {
      rmSync(scratch, { recursive: true, force: true })
    }
  })

  it('reuses the committed timestamp instead of the wall clock', () => {
    // Two check runs moments apart must agree, so a gate can never fail merely
    // because time passed.
    const first = runGenerator(['--check'])
    const second = runGenerator(['--check'])
    expect(first.stdout).toBe(second.stdout)
    expect(first.status).toBe(0)
    expect(second.status).toBe(0)
  })

  it('refuses a pinned timestamp beside --check, which would compare against nothing', () => {
    const result = runGenerator(['--check', '--generated-at', '2026-09-16T00:00:00.000Z'])
    expect(result.status).toBe(1)
    expect(result.stderr).toMatch(/--generated-at cannot be combined with --check/u)
  })

  it('writes the artifact it is asked to write, timestamp included', () => {
    const scratch = mkdtempSync(join(tmpdir(), 'snapshot-write-'))
    try {
      const output = join(scratch, 'written.ts')
      const result = runGenerator(['--generated-at', '2026-09-16T00:00:00.000Z', '--out', output])
      expect(result.status).toBe(0)
      expect(result.stdout).toMatch(/wrote .*schema 1, \d+ models\.dev provider\(s\)/u)
      // A pinned timestamp makes the write reproducible, so a second run is a no-op.
      const first = readFileSync(output, 'utf8')
      expect(first).toContain('"generatedAt": "2026-09-16T00:00:00.000Z"')
      expect(runGenerator(['--check', '--out', output]).status).toBe(0)
      expect(readFileSync(output, 'utf8')).toBe(first)
    } finally {
      rmSync(scratch, { recursive: true, force: true })
    }
  })
})
